import type { Word } from '@/types/IWord'

const words: Word[] = [
  {
    word: 'hi',
    transcription: '[haɪ]',
    reading: 'хай',
    sound: '',
    translate: 'привет',
  },
  {
    word: 'hello',
    transcription: `['he'ləu]`,
    reading: 'хэлоу',
    sound: '',
    translate: 'привет',
  },
  {
    word: 'Big',
    transcription: '[bɪɡ]',
    reading: 'биг',
    sound: '',
    translate: 'большой',
  },
  {
    word: 'Good',
    transcription: '[ɡʊd]',
    reading: 'гуд',
    sound: '',
    translate: 'хороший',
  },
  {
    word: 'Bad',
    transcription: '[bæd]',
    reading: 'бэд',
    sound: '',
    translate: 'плохой',
  },
  {
    word: 'Beautiful',
    transcription: '[ˈbjuːtəfəl]',
    reading: 'бьютифул',
    sound: '',
    translate: 'красивый',
  },
  {
    word: 'Ugly',
    transcription: '[ˈʌɡli]',
    reading: 'агли',
    sound: '',
    translate: 'уродливый',
  },
  {
    word: 'Expensive',
    transcription: '[ɪkˈspɛnsɪv]',
    reading: 'икспенсив',
    sound: '',
    translate: 'дорогой',
  },
  {
    word: 'Cheap',
    transcription: '[ʧi:p]',
    reading: 'чип',
    sound: '',
    translate: 'дешевый',
  },
  {
    word: 'Old',
    transcription: '[oʊld]',
    reading: 'оулд',
    sound: '',
    translate: 'старый',
  },
  {
    word: 'Young',
    transcription: '[jʌŋ]',
    reading: 'янг',
    sound: '',
    translate: 'молодой',
  },
  {
    word: 'Slow',
    transcription: '[sloʊ]',
    reading: 'слоу',
    sound: '',
    translate: 'медленный',
  },
  {
    word: 'Fast',
    transcription: '[fæst]',
    reading: 'фаст',
    sound: '',
    translate: 'быстрый',
  },
  {
    word: 'Difficult',
    transcription: '[ˈdɪfɪkəlt]',
    reading: 'дификълт',
    sound: '',
    translate: 'сложный',
  },
  {
    word: 'Easy',
    transcription: '[ˈizi]',
    reading: 'изи',
    sound: '',
    translate: 'легкий',
  },
  {
    word: 'Cold',
    transcription: '[koʊld]',
    reading: 'коулд',
    sound: '',
    translate: 'холодный',
  },
  {
    word: 'Hot',
    transcription: '[hɑt]',
    reading: 'хот',
    sound: '',
    translate: 'горячий',
  },
  {
    word: 'apple',
    transcription: '[ˈæpl]',
    reading: 'эпл',
    sound: '',
    translate: 'яблоко',
  },
  {
    word: 'banana',
    transcription: '[bəˈnɑː.nə]',
    reading: 'бəнанə',
    sound: '',
    translate: 'банан',
  },
  {
    word: 'cat',
    transcription: '[kæt]',
    reading: 'кэт',
    sound: '',
    translate: 'кошка',
  },
  {
    word: 'dog',
    transcription: '[dɔːɡ]',
    reading: 'дог',
    sound: '',
    translate: 'собака',
  },
  {
    word: 'elephant',
    transcription: '[ˈɛl.ɪ.fənt]',
    reading: 'элəфəнт',
    sound: '',
    translate: 'слон',
  },
  {
    word: 'fish',
    transcription: '[fɪʃ]',
    reading: 'фиш',
    sound: '',
    translate: 'рыба',
  },
  {
    word: 'guitar',
    transcription: '[ɡɪˈtɑːr]',
    reading: 'гитар',
    sound: '',
    translate: 'гитара',
  },
  {
    word: 'house',
    transcription: '[haʊs]',
    reading: 'хаус',
    sound: '',
    translate: 'дом',
  },
  {
    word: 'igloo',
    transcription: '[ˈɪɡ.luː]',
    reading: 'иглу',
    sound: '',
    translate: 'иглу',
  },
  {
    word: 'jelly',
    transcription: '[ˈdʒɛli]',
    reading: 'джелли',
    sound: '',
    translate: 'желе',
  },
  {
    word: 'sun',
    transcription: '[sʌn]',
    reading: 'сан',
    sound: '',
    translate: 'солнце',
  },
  {
    word: 'tree',
    transcription: '[triː]',
    reading: 'три',
    sound: '',
    translate: 'дерево',
  },
]
export default words
